---
service:
    port: ":8080"
    root: ""
db:
  dbType: mysql
  sqlite3:
    filePath:"./qna.db"
  mysql:
    host: "127.0.0.1"
    port: 3306
    databaseName: "QnA"
    user: "root"
    password: 12345678
---